In [2]:
library(dplyr)
library(readxl)
library(psych)
library(fBasics)
library(readr)

In [3]:
df  <- read_csv('Olympic.csv')

Rows: 116949 Columns: 15

-- Column specification ------------------------------------------------------------------------------------------------
Delimiter: ","
chr (10): Name, Sex, Team, NOC, Games, Season, City, Sport, Event, Medal
dbl  (5): ID, Age, Height, Weight, Year


i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [4]:
df

       ID     Name                               Sex Age Height Weight
1       1     A Dijiang                          M   24  180    80
2       2     A Lamusi                           M   23  170    60
3       3     Gunnar Nielsen Aaby                M   24   NA    NA
4       4     Edgar Lindenau Aabye               M   34   NA    NA
5       5     Christine Jacoba Aaftink           F   21  185    82
6       5     Christine Jacoba Aaftink           F   21  185    82
7       5     Christine Jacoba Aaftink           F   25  185    82
8       5     Christine Jacoba Aaftink           F   25  185    82
9       5     Christine Jacoba Aaftink           F   27  185    82
10      5     Christine Jacoba Aaftink           F   27  185    82
11      6     Per Knut Aaland                    M   31  188    75
12      6     Per Knut Aaland                    M   31  188    75
13      6     Per Knut Aaland                    M   31  188    75
14      6     Per Knut Aaland                    M   31  188    75
15      6     Per Knut Aaland                    M   33  188    75
16      6     Per Knut Aaland                    M   33  188    75
17      6     Per Knut Aaland                    M   33  188    75
18      6     Per Knut Aaland                    M   33  188    75
19      7     John Aalberg                       M   31  183    72
20      7     John Aalberg                       M   31  183    72
21      7     John Aalberg                       M   31  183    72
22      7     John Aalberg                       M   31  183    72
23      7     John Aalberg                       M   33  183    72
24      7     John Aalberg                       M   33  183    72
25      7     John Aalberg                       M   33  183    72
26      7     John Aalberg                       M   33  183    72
27      8     Cornelia "Cor" Aalten (-Strannood) F   18  168    NA
28      8     Cornelia "Cor" Aalten (-Strannood) F   18  168    NA
29      9     Antti Sami Aalto                   M   26  186    96
30     10     Einar Ferdinand "Einari" Aalto     M   26   NA    NA
...    ...    ...                                ... ... ...    ...
116920 135262 Angelo Zorzi                       M   29   NA     NA
116921 135263 Cristian Zorzi                     M   33  184     75
116922 135269 Zou Kai                            M   20  158     55
116923 135269 Zou Kai                            M   20  158     55
116924 135269 Zou Kai                            M   20  158     55
116925 135269 Zou Kai                            M   24  158     55
116926 135269 Zou Kai                            M   24  158     55
116927 135270 Zou Shiming                        M   27  165     49
116928 135270 Zou Shiming                        M   31  165     49
116929 135288 Zdravko Zovko                      M   29  183     80
116930 131462 Carolyn Virginia Wood              F   14  167     60
116931 135294 Vedran Zrni                        M   24  188     80
116932 135313 Gyula Zsivtzky                     M   31  190    102
116933  26731 Donna Elizabeth de Varona (-Pinto) F   13  168     61
116934 135343 Aleksandr Yuryevich Zubkov         M   39  189    102
116935 135343 Aleksandr Yuryevich Zubkov         M   39  189    102
116936 135355 Sergey Mikhaylovich Zubov          M   21  186     91
116937 135366 Francesco Zucchetti                M   22   NA     NA
116938 135414 Andreas Zlow                       M   22  175     61
116939 135415 Robertas ulpa                      M   20  193     82
116940 135465 Pirmin Zurbriggen                  M   25  183     83
116941 135474 Albert Hermann Zrner               M   18   NA     NA
116942 135481 Jules Alexis "Louis" Zutter        M   30   NA     NA
116943  37398 Fu Mingxia                         F   13  160     48
116944  39866 Marjorie Gestring (-Redlick)       F   13   NA     NA
116945 135503 Zurab Zviadauri                    M   23  182     90
116946  60384 Kim Yun-Mi                         F   13  160     48
116947 135523 Ronald Ferdinand "Ron" Zwerver     M   29  200     93
116948 135545 Henk Jan Zwolle                    M   31  197     93
116949 100797 Aileen Muriel Riggin (-Soule)      F   13  142     NA
       Team           NOC Games       Year Season City
1      China          CHN 1992 Summer 1992 Summer Barcelona
2      China          CHN 2012 Summer 2012 Summer London
3      Denmark        DEN 1920 Summer 1920 Summer Antwerpen
4      Denmark/Sweden DEN 1900 Summer 1900 Summer Paris
5      Netherlands    NED 1988 Winter 1988 Winter Calgary
6      Netherlands    NED 1988 Winter 1988 Winter Calgary
7      Netherlands    NED 1992 Winter 1992 Winter Albertville
8      Netherlands    NED 1992 Winter 1992 Winter Albertville
9      Netherlands    NED 1994 Winter 1994 Winter Lillehammer
10     Netherlands    NED 1994 Winter 1994 Winter Lillehammer
11     United States  USA 1992 Winter 1992 Winter Albertville
12     United States  USA 1992 Winter 1992 Winter Albertville
13     United States  USA 1992 Winter 1992 Winter Albertville
14     United States  USA 1992 Winter 1992 Winter Albertville
15     United States  USA 1994 Winter 1994 Winter Lillehammer
16     United States  USA 1994 Winter 1994 Winter Lillehammer
17     United States  USA 1994 Winter 1994 Winter Lillehammer
18     United States  USA 1994 Winter 1994 Winter Lillehammer
19     United States  USA 1992 Winter 1992 Winter Albertville
20     United States  USA 1992 Winter 1992 Winter Albertville
21     United States  USA 1992 Winter 1992 Winter Albertville
22     United States  USA 1992 Winter 1992 Winter Albertville
23     United States  USA 1994 Winter 1994 Winter Lillehammer
24     United States  USA 1994 Winter 1994 Winter Lillehammer
25     United States  USA 1994 Winter 1994 Winter Lillehammer
26     United States  USA 1994 Winter 1994 Winter Lillehammer
27     Netherlands    NED 1932 Summer 1932 Summer Los Angeles
28     Netherlands    NED 1932 Summer 1932 Summer Los Angeles
29     Finland        FIN 2002 Winter 2002 Winter Salt Lake City
30     Finland        FIN 1952 Summer 1952 Summer Helsinki
...    ...            ... ...         ...  ...    ...
116920 Italy          ITA 1920 Summer 1920 Summer Antwerpen
116921 Italy          ITA 2006 Winter 2006 Winter Torino
116922 China          CHN 2008 Summer 2008 Summer Beijing
116923 China          CHN 2008 Summer 2008 Summer Beijing
116924 China          CHN 2008 Summer 2008 Summer Beijing
116925 China          CHN 2012 Summer 2012 Summer London
116926 China          CHN 2012 Summer 2012 Summer London
116927 China          CHN 2008 Summer 2008 Summer Beijing
116928 China          CHN 2012 Summer 2012 Summer London
116929 Yugoslavia     YUG 1984 Summer 1984 Summer Los Angeles
116930 United States  USA 1960 Summer 1960 Summer Roma
116931 Croatia        CRO 2004 Summer 2004 Summer Athina
116932 Hungary        HUN 1968 Summer 1968 Summer Mexico City
116933 United States  USA 1960 Summer 1960 Summer Roma
116934 Russia-1       RUS 2014 Winter 2014 Winter Sochi
116935 Russia-1       RUS 2014 Winter 2014 Winter Sochi
116936 Unified Team   EUN 1992 Winter 1992 Winter Albertville
116937 Italy          ITA 1924 Summer 1924 Summer Paris
116938 East Germany   GDR 1988 Summer 1988 Summer Seoul
116939 Soviet Union   URS 1980 Summer 1980 Summer Moskva
116940 Switzerland    SUI 1988 Winter 1988 Winter Calgary
116941 Germany        GER 1908 Summer 1908 Summer London
116942 Switzerland    SUI 1896 Summer 1896 Summer Athina
116943 China          CHN 1992 Summer 1992 Summer Barcelona
116944 United States  USA 1936 Summer 1936 Summer Berlin
116945 Georgia        GEO 2004 Summer 2004 Summer Athina
116946 South Korea    KOR 1994 Winter 1994 Winter Lillehammer
116947 Netherlands    NED 1996 Summer 1996 Summer Atlanta
116948 Netherlands    NED 1996 Summer 1996 Summer Atlanta
116949 United States  USA 1920 Summer 1920 Summer Antwerpen
       Sport
1      Basketball
2      Judo
3      Football
4      Tug-Of-War
5      Speed Skating
6      Speed Skating
7      Speed Skating
8      Speed Skating
9      Speed Skating
10     Speed Skating
11     Cross Country Skiing
12     Cross Country Skiing
13     Cross Country Skiing
14     Cross Country Skiing
15     Cross Country Skiing
16     Cross Country Skiing
17     Cross Country Skiing
18     Cross Country Skiing
19     Cross Country Skiing
20     Cross Country Skiing
21     Cross Country Skiing
22     Cross Country Skiing
23     Cross Country Skiing
24     Cross Country Skiing
25     Cross Country Skiing
26     Cross Country Skiing
27     Athletics
28     Athletics
29     Ice Hockey
30     Swimming
...    ...
116920 Gymnastics
116921 Cross Country Skiing
116922 Gymnastics
116923 Gymnastics
116924 Gymnastics
116925 Gymnastics
116926 Gymnastics
116927 Boxing
116928 Boxing
116929 Handball
116930 Swimming
116931 Handball
116932 Athletics
116933 Swimming
116934 Bobsleigh
116935 Bobsleigh
116936 Ice Hockey
116937 Cycling
116938 Boxing
116939 Swimming
116940 Alpine Skiing
116941 Diving
116942 Gymnastics
116943 Diving
116944 Diving
116945 Judo
116946 Short Track Speed Skating
116947 Volleyball
116948 Rowing
116949 Diving
       Event                                                Medal
1      Basketball Men's Basketball                          NA
2      Judo Men's Extra-Lightweight                         NA
3      Football Men's Football                              NA
4      Tug-Of-War Men's Tug-Of-War                          Gold
5      Speed Skating Women's 500 metres                     NA
6      Speed Skating Women's 1,000 metres                   NA
7      Speed Skating Women's 500 metres                     NA
8      Speed Skating Women's 1,000 metres                   NA
9      Speed Skating Women's 500 metres                     NA
10     Speed Skating Women's 1,000 metres                   NA
11     Cross Country Skiing Men's 10 kilometres             NA
12     Cross Country Skiing Men's 50 kilometres             NA
13     Cross Country Skiing Men's 10/15 kilometres Pursuit  NA
14     Cross Country Skiing Men's 4 x 10 kilometres Relay   NA
15     Cross Country Skiing Men's 10 kilometres             NA
16     Cross Country Skiing Men's 30 kilometres             NA
17     Cross Country Skiing Men's 10/15 kilometres Pursuit  NA
18     Cross Country Skiing Men's 4 x 10 kilometres Relay   NA
19     Cross Country Skiing Men's 10 kilometres             NA
20     Cross Country Skiing Men's 50 kilometres             NA
21     Cross Country Skiing Men's 10/15 kilometres Pursuit  NA
22     Cross Country Skiing Men's 4 x 10 kilometres Relay   NA
23     Cross Country Skiing Men's 10 kilometres             NA
24     Cross Country Skiing Men's 30 kilometres             NA
25     Cross Country Skiing Men's 10/15 kilometres Pursuit  NA
26     Cross Country Skiing Men's 4 x 10 kilometres Relay   NA
27     Athletics Women's 100 metres                         NA
28     Athletics Women's 4 x 100 metres Relay               NA
29     Ice Hockey Men's Ice Hockey                          NA
30     Swimming Men's 400 metres Freestyle                  NA
...    ...                                                  ...
116920 Gymnastics Men's Team All-Around                     Gold
116921 Cross Country Skiing Men's 4 x 10 kilometres Relay   Gold
116922 Gymnastics Men's Team All-Around                     Gold
116923 Gymnastics Men's Floor Exercise                      Gold
116924 Gymnastics Men's Horizontal Bar                      Gold
116925 Gymnastics Men's Team All-Around                     Gold
116926 Gymnastics Men's Floor Exercise                      Gold
116927 Boxing Men's Light-Flyweight                         Gold
116928 Boxing Men's Light-Flyweight                         Gold
116929 Handball Men's Handball                              Gold
116930 Swimming Women's 4 x 100 metres Medley Relay         Gold
116931 Handball Men's Handball                              Gold
116932 Athletics Men's Hammer Throw                         Gold
116933 Swimming Women's 4 x 100 metres Freestyle Relay      Gold
116934 Bobsleigh Men's Two                                  Gold
116935 Bobsleigh Men's Four                                 Gold
116936 Ice Hockey Men's Ice Hockey                          Gold
116937 Cycling Men's Team Pursuit, 4,000 metres             Gold
116938 Boxing Men's Lightweight                             Gold
116939 Swimming Men's 200 metres Breaststroke               Gold
116940 Alpine Skiing Men's Downhill                         Gold
116941 Diving Men's Springboard                             Gold
116942 Gymnastics Men's Pommelled Horse                     Gold
116943 Diving Women's Platform                              Gold
116944 Diving Women's Springboard                           Gold
116945 Judo Men's Middleweight                              Gold
116946 Short Track Speed Skating Women's 3,000 metres Relay Gold
116947 Volleyball Men's Volleyball                          Gold
116948 Rowing Men's Coxed Eights                            Gold
116949 Diving Women's Springboard                           Gold

In [5]:
df %>%
head(10)

   ID Name                     Sex Age Height Weight Team           NOC
1  1  A Dijiang                M   24  180    80     China          CHN
2  2  A Lamusi                 M   23  170    60     China          CHN
3  3  Gunnar Nielsen Aaby      M   24   NA    NA     Denmark        DEN
4  4  Edgar Lindenau Aabye     M   34   NA    NA     Denmark/Sweden DEN
5  5  Christine Jacoba Aaftink F   21  185    82     Netherlands    NED
6  5  Christine Jacoba Aaftink F   21  185    82     Netherlands    NED
7  5  Christine Jacoba Aaftink F   25  185    82     Netherlands    NED
8  5  Christine Jacoba Aaftink F   25  185    82     Netherlands    NED
9  5  Christine Jacoba Aaftink F   27  185    82     Netherlands    NED
10 5  Christine Jacoba Aaftink F   27  185    82     Netherlands    NED
   Games       Year Season City        Sport
1  1992 Summer 1992 Summer Barcelona   Basketball
2  2012 Summer 2012 Summer London      Judo
3  1920 Summer 1920 Summer Antwerpen   Football
4  1900 Summer 1900 Summer Paris       Tug-Of-War
5  1988 Winter 1988 Winter Calgary     Speed Skating
6  1988 Winter 1988 Winter Calgary     Speed Skating
7  1992 Winter 1992 Winter Albertville Speed Skating
8  1992 Winter 1992 Winter Albertville Speed Skating
9  1994 Winter 1994 Winter Lillehammer Speed Skating
10 1994 Winter 1994 Winter Lillehammer Speed Skating
   Event                              Medal
1  Basketball Men's Basketball        NA
2  Judo Men's Extra-Lightweight       NA
3  Football Men's Football            NA
4  Tug-Of-War Men's Tug-Of-War        Gold
5  Speed Skating Women's 500 metres   NA
6  Speed Skating Women's 1,000 metres NA
7  Speed Skating Women's 500 metres   NA
8  Speed Skating Women's 1,000 metres NA
9  Speed Skating Women's 500 metres   NA
10 Speed Skating Women's 1,000 metres NA

In [11]:
sum(is.na(df$Height))

[1] 23977

In [13]:
df$Height[is.na(df$Height)] <- mean(df$Height, na.rm = TRUE)

In [14]:
sum(is.na(df$Height))

[1] 0

In [15]:
missing.values %>%
  ggplot() +
    geom_bar(aes(x=key, y=num.missing), stat = 'identity') +
    labs(x='variable', y="number of missing values", title='Number of missing values') +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))===

ERROR: Error in parse(text = x, srcfile = src): <text>:5:61: unexpected '='
4:     labs(x='variable', y="number of missing values", title='Number of missing values') +
5:   theme(axis.text.x = element_text(angle = 45, hjust = 1))===
                                                               ^

In [17]:
missing.values <- df %>%
    gather(key = "key", value = "val") %>%
    mutate(is.missing = is.na(val)) %>%
    group_by(key, is.missing) %>%
    summarise(num.missing = n()) %>%
    filter(is.missing==T) %>%
    select(-is.missing) %>%
    arrange(desc(num.missing))

ERROR: Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'filter': could not find function "gather"